### ISSUE TITLE
TOPのテキストを中央に揃える

### ISSUE THREAD

**Issue by kameiy** [kanonkanon1999/ky#1]
<img width="952" alt="スクリーンショット 2021-06-21 15 56 03" src="https://user-images.githubusercontent.com/4032172/122719758-9cfc0480-d2a9-11eb-85a4-97b2c01eac30.png">

**Comment by kanonkanon1999** [comment]
修正しました！

**Comment by kanonkanon1999** [comment]
修正しました！

**Comment by kameiy** [comment]
確認しました
