### ISSUE TITLE
問い合わせをGoogleFormsに飛ばしたい

### ISSUE THREAD

**Issue by kameiy** [kanonkanon1999/ky#3]
GoogleForms
https://docs.google.com/forms/d/e/1FAIpQLSf-NE_Qvq86aOJkBR13ksuagpcmN7Dkw9G_UQwgiRyJk1IDew/viewform?usp=sf_link

参考
https://qiita.com/sotatakahashi/items/fa077cbf820faca30598

**Comment by kanonkanon1999** [comment]
修正しました！リンクからご確認よろしくお願いいたします。
https://ky.kanonkanon1999.com/

**Comment by kameiy** [comment]
確認しました
